[book]
authors = ["Mike Kamerman, Mats Heusinkveld, Daan Homma, Mark Holtjer, Daniël Lammers"]
description = "The bundled book for all of the phases we went through during the course Process and Safety of the minor Industrial Automation at Saxion University of Applied Sciences during the first semester of the 2023/2024 school year."
language = "en"
multilingual = false
src = "src"
title = "Process and Safety - Group 1"

[preprocessor.plantuml]
plantuml-cmd="mdbook-plantuml.exe"